<?php

namespace App\Services;

class PermissionCatalog
{
    public static function permissions(): array
    {
        return [
            'dashboard.view',
            'roles.view',
            'roles.create',
            'roles.update',
            'roles.delete',
            'permissions.view',
            'permissions.create',
            'permissions.update',
            'permissions.delete',
            'role-permissions.manage',
            'modules.view',
            'modules.create',
            'modules.update',
            'modules.delete',
            'masters.view',
            'masters.manage',
            'users.view',
            'users.manage',
            'inventory.view',
            'inventory.manage',
            'stock-ledger.view',
            'stock-summary.view',
            'overall-stock-summary.view',
            'stock-verification.view',
            'stock-verification.create',
            'stock-verification.edit',
            'stock-verification.submit',
            'stock-verification.approve',
            'stock-verification.cancel',
            'purchase-grn.view',
            'purchase-grn.manage',
            'bom.view',
            'bom.manage',
            'production.view',
            'production.manage',
            'production.post',
            'production.cancel',
            'wastage.view',
            'wastage.manage',
            'wastage.post',
            'wastage.cancel',
            'wastage-reuse.view',
            'wastage-reuse.manage',
            'wastage-reuse.post',
            'wastage-reuse.cancel',
            'dispatch.view',
            'dispatch.manage',
            'accounts.view',
            'accounts.manage',
            'reports.view',
            'audit.view',
        ];
    }

    public static function navigation(): array
    {
        return [
            ['title' => 'Dashboard', 'path' => '/dashboard', 'section' => 'Dashboard', 'permission' => 'dashboard.view', 'icon' => 'layout-dashboard'],
            ['title' => 'Item Master', 'path' => '/items', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'package'],
            ['title' => 'Material Type', 'path' => '/material-types', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'layers-3'],
            ['title' => 'UOM Master', 'path' => '/uoms', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'ruler'],
            ['title' => 'Location Master', 'path' => '/locations', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'map-pin'],
            ['title' => 'Customer Master', 'path' => '/customers', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'user-round'],
            ['title' => 'Supplier Master', 'path' => '/suppliers', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'truck'],
            ['title' => 'State Master', 'path' => '/states', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'map'],
            ['title' => 'Team Master', 'path' => '/teams', 'section' => 'Master', 'permission' => 'masters.view', 'icon' => 'network'],
            ['title' => 'GRN', 'path' => '/grn', 'section' => 'Inventory', 'permission' => 'purchase-grn.view', 'icon' => 'package-check'],
            ['title' => 'Stock Ledger', 'path' => '/stock-ledger', 'section' => 'Inventory', 'permission' => 'stock-ledger.view', 'icon' => 'clipboard-list'],
            ['title' => 'Raw Material Stock Summary', 'path' => '/stock-summary', 'section' => 'Inventory', 'permission' => 'stock-summary.view', 'icon' => 'chart-column'],
            ['title' => 'OverAll Stock Summary', 'path' => '/overall-stock-summary', 'section' => 'Inventory', 'permission' => 'overall-stock-summary.view', 'icon' => 'chart-column'],
            ['title' => 'Finished Product Stock Summary', 'path' => '/finished-product-stock-summary', 'section' => 'Inventory', 'permission' => 'overall-stock-summary.view', 'icon' => 'chart-column'],
            ['title' => 'Wastage Management', 'path' => '/wastage', 'section' => 'Inventory', 'permission' => 'wastage.view', 'icon' => 'chart-column'],
            // ['title' => 'Wastage Adjustment', 'path' => '/wastage-adjustment', 'section' => 'Inventory', 'permission' => 'wastage.manage', 'icon' => 'sliders-horizontal'],
            // ['title' => 'Wastage Report', 'path' => '/wastage-summary', 'section' => 'Inventory', 'permission' => 'wastage.view', 'icon' => 'file-text'],
            ['title' => 'Wastage Reuse', 'path' => '/wastage-reuse', 'section' => 'Inventory', 'permission' => 'wastage-reuse.view', 'icon' => 'recycle'],
            ['title' => 'Stock Verification', 'path' => '/stock-verification', 'section' => 'Inventory', 'permission' => 'stock-verification.view', 'icon' => 'scan-line'],
            ['title' => 'BOM', 'path' => '/bom', 'section' => 'Production', 'permission' => 'bom.view', 'icon' => 'workflow'],
            ['title' => 'Production Entry', 'path' => '/production', 'section' => 'Production', 'permission' => 'production.view', 'icon' => 'factory'],
            ['title' => 'Dispatch Challan', 'path' => '/dispatch-challan', 'section' => 'Dispatch', 'permission' => 'dispatch.view', 'icon' => 'truck'],
            ['title' => 'Team Ledger', 'path' => '/team-ledger', 'section' => 'Dispatch', 'permission' => 'accounts.view', 'icon' => 'book-open'],
            ['title' => 'Team Payments', 'path' => '/team-payments', 'section' => 'Dispatch', 'permission' => 'accounts.view', 'icon' => 'wallet'],
            ['title' => 'Inventory Reports', 'path' => '/inventory-reports', 'section' => 'Reports', 'permission' => 'reports.view', 'icon' => 'clipboard-list'],
            ['title' => 'Production Reports', 'path' => '/production-reports', 'section' => 'Reports', 'permission' => 'reports.view', 'icon' => 'factory'],
            ['title' => 'Dispatch Reports', 'path' => '/dispatch-reports', 'section' => 'Reports', 'permission' => 'reports.view', 'icon' => 'truck'],
            ['title' => 'Payment Reports', 'path' => '/payment-reports', 'section' => 'Reports', 'permission' => 'reports.view', 'icon' => 'receipt-text'],
            ['title' => 'Users', 'path' => '/users', 'section' => 'Administration', 'permission' => 'users.view', 'icon' => 'user-cog'],
            ['title' => 'Roles', 'path' => '/roles', 'section' => 'Administration', 'permission' => 'roles.view', 'icon' => 'shield-check'],
            ['title' => 'Permissions', 'path' => '/permissions', 'section' => 'Administration', 'permission' => 'permissions.view', 'icon' => 'key-round'],
            ['title' => 'Modules', 'path' => '/modules', 'section' => 'Administration', 'permission' => 'modules.view', 'icon' => 'blocks'],
            ['title' => 'Settings', 'path' => '/settings', 'section' => 'Administration', 'permission' => 'masters.manage', 'icon' => 'settings-2'],
        ];
    }
}
